--
-- VHDL Package Body renoir_package_library.auto_type_conv
--
-- Created:
--          by - user
--          at - 18:03:03 21/09/99
--
-- Generated by Mentor Graphics' Renoir(TM) 
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;

PACKAGE BODY auto_type_conv IS
-- Size-independent type conversion functions
    -- ren_conv_int - Converts std_ulogic_vector to integer
    FUNCTION ren_conv_int    ( val : std_ulogic_vector ) RETURN  integer IS
    BEGIN
       RETURN conv_integer(unsigned(val));
    END ren_conv_int;

    -- ren_conv_int - Converts std_logic_vector to integer
    FUNCTION ren_conv_int    ( val : std_logic_vector ) RETURN  integer IS
    BEGIN
       RETURN conv_integer(unsigned(val));
    END ren_conv_int;

    -- ren_conv_slv - Converts signed to std_logic_vector
    FUNCTION ren_conv_slv     ( val : signed )     RETURN  std_logic_vector IS
    BEGIN
       RETURN std_logic_vector(val);
    END ren_conv_slv;

    -- ren_conv_slv - Converts unsigned to  std_logic_vector
    FUNCTION ren_conv_slv     ( val : unsigned )   RETURN  std_logic_vector IS
    BEGIN
       RETURN std_logic_vector(val);
    END ren_conv_slv;

    -- ren_conv_suv - Converts signed to std_logic_vector
    FUNCTION ren_conv_suv     ( val : signed )     RETURN  std_ulogic_vector IS
    BEGIN
       RETURN std_ulogic_vector(val);
    END ren_conv_suv;

    -- ren_conv_suv - Converts unsigned to  std_logic_vector
    FUNCTION ren_conv_suv     ( val : unsigned )   RETURN  std_ulogic_vector IS
    BEGIN
       RETURN std_ulogic_vector(val);
    END ren_conv_suv;
   
    -- ren_conv_uns - Converts signed to unsigned
    FUNCTION ren_conv_uns     ( val : signed )     RETURN  unsigned IS
    BEGIN
       RETURN unsigned(val);
    END ren_conv_uns;

    -- ren_conv_uns - Converts std_ulogic_vector to  unsigned
    FUNCTION ren_conv_uns     ( val : std_ulogic_vector )   RETURN  unsigned IS
    BEGIN
       RETURN unsigned(val);
    END ren_conv_uns;

    -- ren_conv_uns - Converts std_logic_vector to  unsigned
    FUNCTION ren_conv_uns     ( val : std_logic_vector )   RETURN  unsigned IS
    BEGIN
       RETURN unsigned(val);
    END ren_conv_uns;

    -- ren_conv_sig - Converts unsigned to signed
    FUNCTION ren_conv_sig     ( val : unsigned )     RETURN  signed IS
    BEGIN
       RETURN signed(val);
    END ren_conv_sig;

    -- ren_conv_sig - Converts std_ulogic_vector to  signed
    FUNCTION ren_conv_sig     ( val : std_ulogic_vector )   RETURN  signed IS
    BEGIN
       RETURN signed(val);
    END ren_conv_sig;

    -- ren_conv_sig - Converts std_logic_vector to  signed
    FUNCTION ren_conv_sig     ( val : std_logic_vector )   RETURN  signed IS
    BEGIN
       RETURN signed(val);
    END ren_conv_sig;


-- Size-specific type conversion functions

    -- ren_conv_slv8 - Converts std_ulogic/std_logic to 8-bit std_logic_vector
    FUNCTION ren_conv_slv8    ( val : std_ulogic ) RETURN  std_logic_vector IS
    BEGIN
       RETURN conv_std_logic_vector(val, 8);
    END ren_conv_slv8;

    -- ren_conv_slv8 - Converts integer to 8-bit std_logic_vector
    FUNCTION ren_conv_slv8    ( val : integer )    RETURN  std_logic_vector IS
    BEGIN
       RETURN conv_std_logic_vector(val, 8);
    END ren_conv_slv8;

     -- ren_conv_suv8 - Converts std_ulogic/std_logic to 8-bit std_ulogic_vector
    FUNCTION ren_conv_suv8    ( val : std_ulogic ) RETURN  std_ulogic_vector IS
    BEGIN
       RETURN std_ulogic_vector(conv_std_logic_vector(val, 8));
    END ren_conv_suv8;

    -- ren_conv_suv8 - Converts integer to 8-bit std_logic_vector
    FUNCTION ren_conv_suv8    ( val : integer )    RETURN  std_ulogic_vector IS
    BEGIN
       RETURN std_ulogic_vector(conv_std_logic_vector(val, 8));
    END ren_conv_suv8;

     -- ren_conv_uns8 - Converts std_ulogic/std_logic to 8-bit unsigned
    FUNCTION ren_conv_uns8    ( val : std_ulogic ) RETURN  unsigned IS
    BEGIN
       RETURN conv_unsigned(val, 8);
    END ren_conv_uns8;

    -- ren_conv_uns8 - Converts integer to 8-bit unsigned
    FUNCTION ren_conv_uns8    ( val : integer )    RETURN  unsigned IS
    BEGIN
       RETURN conv_unsigned(val, 8);
    END ren_conv_uns8;

     -- ren_conv_sig8 - Converts std_ulogic/std_logic to 8-bit signed
    FUNCTION ren_conv_sig8    ( val : std_ulogic ) RETURN  signed IS
    BEGIN
       RETURN conv_signed(val, 8);
    END ren_conv_sig8;

    -- ren_conv_sig8 - Converts integer to 8-bit signed
    FUNCTION ren_conv_sig8    ( val : integer )    RETURN  signed IS
    BEGIN
       RETURN conv_signed(val, 8);
    END ren_conv_sig8;


END auto_type_conv;
