--
-- VHDL Package Header renoir_package_library.auto_type_conv
--
-- Created:
--          by - user
--          at - 18:02:10 23/09/99
--
-- Generated by Mentor Graphics' Renoir(TM) 
--
LIBRARY IEEE; 
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;

PACKAGE auto_type_conv IS
-- Size-independent type conversion functions
    FUNCTION ren_conv_int     ( val : std_ulogic_vector )    RETURN  integer;
    FUNCTION ren_conv_int     ( val : std_logic_vector )     RETURN  integer;

    FUNCTION ren_conv_slv     ( val : signed )     RETURN  std_logic_vector;
    FUNCTION ren_conv_slv     ( val : unsigned )   RETURN  std_logic_vector;

    FUNCTION ren_conv_suv     ( val : signed )     RETURN  std_ulogic_vector;
    FUNCTION ren_conv_suv     ( val : unsigned )   RETURN  std_ulogic_vector;
    
    FUNCTION ren_conv_uns     ( val : std_ulogic_vector )    RETURN  unsigned;
    FUNCTION ren_conv_uns     ( val : std_logic_vector )     RETURN  unsigned;
    FUNCTION ren_conv_uns     ( val : signed )               RETURN  unsigned;
    
    FUNCTION ren_conv_sig     ( val : std_ulogic_vector )    RETURN  signed;
    FUNCTION ren_conv_sig     ( val : std_logic_vector )     RETURN  signed;
    FUNCTION ren_conv_sig     ( val : unsigned )             RETURN  signed;

-- Size-specific type conversion functions
    FUNCTION ren_conv_slv8    ( val : std_ulogic ) RETURN  std_logic_vector;
    FUNCTION ren_conv_slv8    ( val : integer )    RETURN  std_logic_vector;
    FUNCTION ren_conv_suv8    ( val : std_ulogic ) RETURN  std_ulogic_vector;
    FUNCTION ren_conv_suv8    ( val : integer )    RETURN  std_ulogic_vector;
    FUNCTION ren_conv_uns8    ( val : std_ulogic )           RETURN  unsigned;
    FUNCTION ren_conv_uns8    ( val : integer )              RETURN  unsigned;
    FUNCTION ren_conv_sig8    ( val : std_ulogic )           RETURN  signed;
    FUNCTION ren_conv_sig8    ( val : integer )              RETURN  signed;
 
END auto_type_conv;
