//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V@PRODUCT_VERSION@
//   UVM Register Kit version @OVM_KIT_VERSION@
//----------------------------------------------------------------------
// Project         : @PROJECT_NAME@
// Unit            : @PACKAGE_NAME@
// File            : @FILE_NAME@
//----------------------------------------------------------------------
// Created by      : @USER@
// Creation Date   : @CREATION_DATE@
//----------------------------------------------------------------------
// Title           : @PROJECT_TITLE@
//
// Description     : @PROJECT_DESCRIPTION@
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// @PACKAGE_NAME@
//----------------------------------------------------------------------
package @PACKAGE_NAME@;

@EXTRA_IMPORTS@
@EXTRA_INCLUDES@
@DEFINE_REGISTER_CLASSES@

@DEFINE_REGISTER_FILES@

@DEFINE_BLOCKS@

endpackage
