-- VHDL Entity alien_game_lib.c3_hit_defeated.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-707-SPC)
--          at - 19:38:52 13.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_hit_defeated IS
   PORT( 
      clk      : IN     std_logic;
      hit      : IN     std_logic;
      rst      : IN     std_logic;
      defeated : OUT    std_logic
   );

-- Declarations

END c3_hit_defeated ;

--
-- VHDL Architecture alien_game_lib.c3_hit_defeated.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-707-SPC)
--          at - 19:38:51 13.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_hit_defeated IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1 : std_logic;
   SIGNAL dout : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL defeated_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   defeated_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   din1 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(defeated_internal, din1, hit)
   BEGIN
      CASE hit IS
      WHEN '0' => dout <= defeated_internal;
      WHEN '1' => dout <= din1;
      WHEN OTHERS => dout <= 'X';
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   defeated <= defeated_internal;

END struct;
