-- VHDL Entity alien_game_lib.c1_t1_gun_movement.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-703-SPC)
--          at - 12:17:50 28.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t1_gun_movement IS
-- Declarations

END c1_t1_gun_movement ;

--
-- VHDL Architecture alien_game_lib.c1_t1_gun_movement.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-703-SPC)
--          at - 12:17:50 28.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t1_gun_movement IS

   -- Architecture declarations



BEGIN

   -- Instance port mappings.

END struct;
