-- VHDL Entity alien_game_lib.c1_t4_decrementer.symbol
--
-- Created:
--          by - bbhiwa.UNKNOWN (HTC219-720-SPC)
--          at - 12:40:16 26.09.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t4_decrementer IS
   PORT( 
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c1_t4_decrementer ;

--
-- VHDL Architecture alien_game_lib.c1_t4_decrementer.struct
--
-- Created:
--          by - bbhiwa.UNKNOWN (HTC219-720-SPC)
--          at - 12:40:16 26.09.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c1_t4_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry : std_logic;
   SIGNAL cout  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;


   -- Component Declarations
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT full_adder
   PORT (
      x0   : IN     std_logic ;
      x1   : IN     std_logic ;
      x2   : IN     std_logic ;
      cout : OUT    std_logic ;
      sum  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   FOR ALL : full_adder USE ENTITY alien_game_lib.full_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   dout1 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_11' of 'constval'
   dout2 <= '1';

   -- Instance port mappings.
   U_8 : c1_t1_half_adder
      PORT MAP (
         sw0   => x(0),
         sw1   => dout,
         carry => carry,
         sum   => y(0)
      );
   U_0 : full_adder
      PORT MAP (
         x0   => x(1),
         x1   => dout1,
         x2   => carry,
         cout => cout,
         sum  => y(1)
      );
   U_1 : full_adder
      PORT MAP (
         x0   => x(2),
         x1   => dout2,
         x2   => cout,
         cout => OPEN,
         sum  => y(2)
      );

END struct;
