-- VHDL Entity alien_game_lib.c2_t1_hello_led_a.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-704-SPC)
--          at - 12:12:06  7.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_hello_led_a IS
   PORT( 
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_hello_led_a ;

--
-- VHDL Architecture alien_game_lib.c2_t1_hello_led_a.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-704-SPC)
--          at - 12:32:26  7.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_hello_led_a IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   x_coord <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   color_BGR <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   y_coord <= "01000000";

   -- Instance port mappings.

END struct;
