-- VHDL Entity alien_game_lib.c3_current_point.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-707-SPC)
--          at - 18:54:18 13.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_current_point IS
   PORT( 
      clk           : IN     std_logic;
      rst           : IN     std_logic;
      x_coord       : IN     std_logic_vector (7 DOWNTO 0);
      current_point : OUT    std_logic
   );

-- Declarations

END c3_current_point ;

--
-- VHDL Architecture alien_game_lib.c3_current_point.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-703-SPC)
--          at - 12:44:35 28.10.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_current_point IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL current_point_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   current_point_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_2reg_cval <= '1';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout1;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(current_point_internal, x_coord, dout)
   BEGIN
      CASE dout IS
      WHEN '0' => dout1 <= current_point_internal;
      WHEN '1' => dout1 <= x_coord(7);
      WHEN OTHERS => dout1 <= 'X';
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'or'
   dout <= x_coord(7) OR x_coord(0);

   -- Instance port mappings.

   -- Implicit buffered output assignments
   current_point <= current_point_internal;

END struct;
