-- VHDL Entity alien_game_lib.c4_t2_bullet.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-705-SPC)
--          at - 20:51:37 30.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t2_bullet IS
   PORT( 
      btn                 : IN     std_logic_vector (3 DOWNTO 0);
      clk                 : IN     std_logic;
      enable              : IN     std_logic;
      gun_x_coordinate    : IN     std_logic_vector (7 DOWNTO 0);
      rst_n               : IN     std_logic;
      bullet_x_coordinate : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coordinate : OUT    std_logic_vector (7 DOWNTO 0);
      color               : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c4_t2_bullet ;

--
-- VHDL Architecture alien_game_lib.c4_t2_bullet.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-705-SPC)
--          at - 20:51:37 30.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t2_bullet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL data_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout     : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout0    : std_logic;
   SIGNAL dout1    : std_logic;
   SIGNAL dout2    : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout3    : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout5    : std_logic;
   SIGNAL q        : std_logic;
   SIGNAL rst      : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL bullet_y_coordinate_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(23 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_9' of 'adff'
   SIGNAL mw_U_9reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_10' of 'adff'
   SIGNAL mw_U_10reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_13' of 'split'
   SIGNAL mw_U_13temp_din : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT right_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : right_shifter USE ENTITY alien_game_lib.right_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   color <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '1') THEN
         mw_U_1reg_cval <= "000000000000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= dout3;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   bullet_x_coordinate <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '1') THEN
         mw_U_3reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= gun_x_coordinate;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   bullet_y_coordinate_internal <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (dout1, rst)
   BEGIN
      IF (rst = '1') THEN
         mw_U_4reg_cval <= "01000000";
      ELSIF (dout1'EVENT AND dout1='1') THEN
         mw_U_4reg_cval <= data_out;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'adff'
   bullet_y_coordinate_internal <= mw_U_9reg_cval;
   u_9seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '1') THEN
         mw_U_9reg_cval <= "01000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_9reg_cval <= bullet_y_coordinate_internal;
      END IF;
   END PROCESS u_9seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'adff'
   q <= mw_U_10reg_cval;
   u_10seq_proc: PROCESS (btn(0), rst)
   BEGIN
      IF (rst = '1') THEN
         mw_U_10reg_cval <= '0';
      ELSIF (btn(0)'EVENT AND btn(0)='1') THEN
         mw_U_10reg_cval <= dout5;
      END IF;
   END PROCESS u_10seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout1 <= NOT(dout0) AND q AND enable;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   dout2 <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_11' of 'constval'
   dout5 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_2' of 'inv'
   rst <= NOT(rst_n);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'mux'
   u_7combo_proc: PROCESS(dout2, dout, dout0)
   BEGIN
      CASE dout0 IS
      WHEN '0' => dout3 <= dout2;
      WHEN '1' => dout3 <= dout;
      WHEN OTHERS => dout3 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_7combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'split'
   mw_U_13temp_din <= bullet_y_coordinate_internal;
   u_13combo_proc: PROCESS (mw_U_13temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_13temp_din(7 DOWNTO 0);
      dout0 <= temp_din(0);
   END PROCESS u_13combo_proc;

   -- Instance port mappings.
   U_8 : right_shifter
      PORT MAP (
         data_in  => bullet_y_coordinate_internal,
         data_out => data_out
      );

   -- Implicit buffered output assignments
   bullet_y_coordinate <= bullet_y_coordinate_internal;

END struct;
