-- VHDL Entity alien_game_lib.c4_t1_gun_module_final.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-712-SPC)
--          at - 17:56:22 13.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_gun_module_final IS
-- Declarations

END c4_t1_gun_module_final ;

--
-- VHDL Architecture alien_game_lib.c4_t1_gun_module_final.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-712-SPC)
--          at - 17:56:22 13.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_gun_module_final IS

   -- Architecture declarations



BEGIN

   -- Instance port mappings.

END struct;
