-- VHDL Entity alien_game_lib.c4_t1_m3.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-720-SPC)
--          at - 00:34:43  2.12.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_m3 IS
   PORT( 
      btn          : IN     std_logic_vector (3 DOWNTO 0);
      clk          : IN     std_logic;
      enable       : IN     std_logic;
      rst_n        : IN     std_logic;
      x_coordinate : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t1_m3 ;

--
-- VHDL Architecture alien_game_lib.c4_t1_m3.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-720-SPC)
--          at - 00:34:43  2.12.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_m3 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0  : std_logic_vector(2 DOWNTO 0);
   SIGNAL din1  : std_logic;
   SIGNAL din2  : std_logic;
   SIGNAL dout  : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(1 DOWNTO 0);
   SIGNAL y     : std_logic_vector(2 DOWNTO 0);
   SIGNAL y1    : std_logic_vector(2 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL x_coordinate_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT c1_t3_incrementer
   PORT (
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c1_t4_decrementer
   PORT (
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t3_bin2onehot
   PORT (
      binary_in   : IN     std_logic_vector (2 DOWNTO 0);
      one_hot_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t3_incrementer USE ENTITY alien_game_lib.c1_t3_incrementer;
   FOR ALL : c1_t4_decrementer USE ENTITY alien_game_lib.c1_t4_decrementer;
   FOR ALL : c2_t3_bin2onehot USE ENTITY alien_game_lib.c2_t3_bin2onehot;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   din0 <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_7reg_cval <= "000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_7reg_cval <= dout;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'and'
   din2 <= btn(3) AND NOT(x_coordinate_internal(2)) AND enable;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'and'
   din1 <= btn(1) AND NOT(x_coordinate_internal(7)) AND enable;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'merge'
   dout2 <= din2 & din1;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(din0, y1, y, dout2)
   BEGIN
      CASE dout2 IS
      WHEN "00" => dout <= din0;
      WHEN "01" => dout <= y1;
      WHEN "10" => dout <= y;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_1 : c1_t3_incrementer
      PORT MAP (
         x => din0,
         y => y1
      );
   U_2 : c1_t4_decrementer
      PORT MAP (
         x => din0,
         y => y
      );
   U_9 : c2_t3_bin2onehot
      PORT MAP (
         binary_in   => din0,
         one_hot_out => x_coordinate_internal
      );

   -- Implicit buffered output assignments
   x_coordinate <= x_coordinate_internal;

END struct;
