-- VHDL Entity alien_game_lib.c4_t2_bullet.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-705-SPC)
--          at - 20:24:20 30.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t2_bullet IS
   PORT( 
      btn                  : IN     std_logic_vector (3 DOWNTO 0);
      clk                  : IN     std_logic;
      enable               : IN     std_logic;
      gun_x_coordinates    : IN     std_logic_vector (7 DOWNTO 0);
      rst_n                : IN     std_logic;
      bullet_x_coordinates : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coordinates : OUT    std_logic_vector (7 DOWNTO 0);
      color                : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c4_t2_bullet ;

--
-- VHDL Architecture alien_game_lib.c4_t2_bullet.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-705-SPC)
--          at - 20:24:19 30.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t2_bullet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d     : std_logic_vector(7 DOWNTO 0);
   SIGNAL d1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL din0  : std_logic;
   SIGNAL din1  : std_logic;
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(23 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_13' of 'split'
   SIGNAL mw_U_13temp_din : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT right_shifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : right_shifter USE ENTITY alien_game_lib.right_shifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   din1 <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (btn(0), dout5)
   BEGIN
      IF (dout5 = '1') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (btn(0)'EVENT AND btn(0)='1') THEN
         mw_U_0reg_cval <= dout3;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   bullet_x_coordinates <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, dout5)
   BEGIN
      IF (dout5 = '1') THEN
         mw_U_1reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= gun_x_coordinates;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   color <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, dout5)
   BEGIN
      IF (dout5 = '1') THEN
         mw_U_2reg_cval <= "000000000000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout2;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   d <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (dout4, dout5)
   BEGIN
      IF (dout5 = '1') THEN
         mw_U_3reg_cval <= "00000000";
      ELSIF (dout4'EVENT AND dout4='1') THEN
         mw_U_3reg_cval <= d1;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   bullet_y_coordinates <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, dout5)
   BEGIN
      IF (dout5 = '1') THEN
         mw_U_4reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= d;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   dout4 <= NOT(din0) AND din1 AND enable;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   dout1 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_11' of 'constval'
   dout <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   dout3 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_9' of 'inv'
   dout5 <= NOT(rst_n);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'mux'

   -- ModuleWare code(v1.12) for instance 'U_13' of 'split'
   mw_U_13temp_din <= d;
   u_13combo_proc: PROCESS (mw_U_13temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_13temp_din(7 DOWNTO 0);
      din0 <= temp_din(0);
   END PROCESS u_13combo_proc;

   -- Instance port mappings.
   U_5 : right_shifter
      PORT MAP (
         data_in  => d,
         data_out => d1
      );

END struct;
