-- VHDL Entity alien_game_lib.c4_t1_gun_module.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-710-SPC)
--          at - 23:45:09  1.12.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_gun_module IS
   PORT( 
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic;
      enable      : IN     std_logic;
      gun_px_idx  : IN     std_logic_vector (1 DOWNTO 0);
      rst_n       : IN     std_logic;
      gun_color   : OUT    std_logic_vector (23 DOWNTO 0);
      gun_x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      gun_y_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t1_gun_module ;

--
-- VHDL Architecture alien_game_lib.c4_t1_gun_module.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-720-SPC)
--          at - 00:35:28  2.12.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_gun_module IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0  : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1  : std_logic_vector(7 DOWNTO 0);
   SIGNAL din2  : std_logic_vector(7 DOWNTO 0);
   SIGNAL din3  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c4_t1_m1
   PORT (
      btn          : IN     std_logic_vector (3 DOWNTO 0);
      clk          : IN     std_logic ;
      enable       : IN     std_logic ;
      rst_n        : IN     std_logic ;
      x_coordinate : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_t1_m2
   PORT (
      btn          : IN     std_logic_vector (3 DOWNTO 0);
      clk          : IN     std_logic ;
      enable       : IN     std_logic ;
      rst_n        : IN     std_logic ;
      x_coordinate : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_t1_m3
   PORT (
      btn          : IN     std_logic_vector (3 DOWNTO 0);
      clk          : IN     std_logic ;
      enable       : IN     std_logic ;
      rst_n        : IN     std_logic ;
      x_coordinate : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_m1 USE ENTITY alien_game_lib.c4_t1_m1;
   FOR ALL : c4_t1_m2 USE ENTITY alien_game_lib.c4_t1_m2;
   FOR ALL : c4_t1_m3 USE ENTITY alien_game_lib.c4_t1_m3;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout <= gun_px_idx(1) AND gun_px_idx(0);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   gun_color <= x"FFFF00";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout1 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout2 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(din0, din1, din2, din3, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => gun_x_coord <= din0;
      WHEN "01" => gun_x_coord <= din1;
      WHEN "10" => gun_x_coord <= din2;
      WHEN "11" => gun_x_coord <= din3;
      WHEN OTHERS => gun_x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(dout1, dout2, dout)
   BEGIN
      CASE dout IS
      WHEN '0' => gun_y_coord <= dout1;
      WHEN '1' => gun_y_coord <= dout2;
      WHEN OTHERS => gun_y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- Instance port mappings.
   U_1 : c4_t1_m1
      PORT MAP (
         btn          => btn,
         clk          => clk,
         enable       => enable,
         rst_n        => rst_n,
         x_coordinate => din0
      );
   U_0 : c4_t1_m2
      PORT MAP (
         btn          => btn,
         clk          => clk,
         enable       => enable,
         rst_n        => rst_n,
         x_coordinate => din1
      );
   U_7 : c4_t1_m2
      PORT MAP (
         btn          => btn,
         clk          => clk,
         enable       => enable,
         rst_n        => rst_n,
         x_coordinate => din3
      );
   U_2 : c4_t1_m3
      PORT MAP (
         btn          => btn,
         clk          => clk,
         enable       => enable,
         rst_n        => rst_n,
         x_coordinate => din2
      );

END struct;
