-- VHDL Entity alien_game_lib.c5_t1_write_sequencer.symbol
--
-- Created:
--          by - mqange.mqange (pikkuhaikara.lin.tuni.fi)
--          at - 15:17:53 11/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_write_sequencer IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      write_ready    : IN     std_logic;
      enable         : OUT    std_logic;
      frame_done     : OUT    std_logic;
      gun_px_idx     : OUT    std_logic_vector (1 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic
   );

-- Declarations

END c5_t1_write_sequencer ;

--
-- VHDL Architecture alien_game_lib.c5_t1_write_sequencer.fsm
--
-- Created:
--          by - mqange.mqange (pikkuhaikara.lin.tuni.fi)
--          at - 15:17:53 11/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c5_t1_write_sequencer IS

   TYPE STATE_TYPE IS (
      Start,
      WR,
      s0,
      led_pos_4,
      s1,
      s2,
      s3,
      led_pos_1,
      led_pos_2,
      led_pos_3
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(1 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(1 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s0 : std_logic;
   SIGNAL csm_to_s1 : std_logic;
   SIGNAL csm_to_s3 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rising_edge(clk)) THEN
         IF (rst_n = '0') THEN
            current_state <= next_state;
            csm_timer <= csm_next_timer;
         END IF;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      write_ready
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s0 <= '0';
      csm_to_s1 <= '0';
      csm_to_s3 <= '0';
      CASE current_state IS
         WHEN Start => 
            IF (write_ready = '1') THEN 
               next_state <= WR;
            ELSE
               next_state <= Start;
            END IF;
         WHEN WR => 
            next_state <= s0;
            csm_to_s0 <= '1';
         WHEN s0 => 
            IF (csm_timeout = '1') THEN 
               next_state <= led_pos_1;
            ELSE
               next_state <= s0;
            END IF;
         WHEN led_pos_4 => 
            next_state <= s1;
            csm_to_s1 <= '1';
         WHEN s1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s2;
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            next_state <= s3;
            csm_to_s3 <= '1';
         WHEN s3 => 
            IF (csm_timeout = '1') THEN 
               next_state <= Start;
            ELSE
               next_state <= s3;
            END IF;
         WHEN led_pos_1 => 
            next_state <= led_pos_2;
         WHEN led_pos_2 => 
            next_state <= led_pos_3;
         WHEN led_pos_3 => 
            next_state <= led_pos_4;
         WHEN OTHERS =>
            next_state <= Start;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN Start => 
            module_select <= "00";
            gun_px_idx <= "00";
            frame_done <= '0';
         WHEN WR => 
            write <= '1';
            module_select <= "00";
            gun_px_idx <= "00";
            frame_done <= '0';
            enable <= '0';
         WHEN led_pos_4 => 
            write <= '1';
            module_select <= "01";
            gun_px_idx <= "11";
            frame_done <= '0';
            enable <= '0';
         WHEN s1 => 
            write <= '0' ;
            module_select <= "00";
            gun_px_idx <= "00";
            frame_done <= '1';
            enable <= '0';
         WHEN s2 => 
            write <= '0';
            module_select <= "00";
            gun_px_idx <= "00";
            frame_done <= '0';
            enable <= '1';
         WHEN led_pos_1 => 
            write <= '1';
            module_select <= "01";
            gun_px_idx <= "00";
            frame_done <= '0';
            enable <= '0';
         WHEN led_pos_2 => 
            write <= '1';
            module_select <= "01";
            gun_px_idx <= "01";
            frame_done <= '0';
            enable <= '0';
         WHEN led_pos_3 => 
            write <= '1';
            module_select <= "01";
            gun_px_idx <= "10";
            frame_done <= '0';
            enable <= '0';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s0,
      csm_to_s1,
      csm_to_s3
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s0 = '1') THEN
         csm_next_timer <= "01"; -- no cycles(2)-1=1
      ELSIF (csm_to_s1 = '1') THEN
         csm_next_timer <= "01"; -- no cycles(2)-1=1
      ELSIF (csm_to_s3 = '1') THEN
         csm_next_timer <= "01"; -- no cycles(2)-1=1
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
