-- VHDL Entity alien_game_lib.c6_t2_y_coord_vic.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-722-SPC)
--          at - 17:21:42 22.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t2_y_coord_vic IS
   PORT( 
      mux_signal : IN     std_logic_vector (3 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c6_t2_y_coord_vic ;

--
-- VHDL Architecture alien_game_lib.c6_t2_y_coord_vic.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-722-SPC)
--          at - 17:30:26 22.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c6_t2_y_coord_vic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0  : std_logic_vector(7 DOWNTO 0);
   SIGNAL din10 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din15 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din4  : std_logic_vector(7 DOWNTO 0);
   SIGNAL din8  : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   din0 <= "00000010";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   din4 <= "00000100";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   din8 <= "00010000";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   din10 <= "00100000";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   din15 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(din0, din4, din8, din10, din15, mux_signal)
   BEGIN
      CASE mux_signal IS
      WHEN "0000" => y_coord <= din0;
      WHEN "0100" => y_coord <= din4;
      WHEN "0101" => y_coord <= din4;
      WHEN "0111" => y_coord <= din4;
      WHEN "1000" => y_coord <= din8;
      WHEN "1010" => y_coord <= din10;
      WHEN "1100" => y_coord <= din15;
      WHEN "1101" => y_coord <= din15;
      WHEN "1111" => y_coord <= din15;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- Instance port mappings.

END struct;
