-- VHDL Entity alien_game_lib.c6_t1_hit_detector.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-722-SPC)
--          at - 21:19:40 25.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t1_hit_detector IS
   PORT( 
      alien_x_coordinate : IN     std_logic_vector (7 DOWNTO 0);
      btn                : IN     std_logic;
      clk                : IN     std_logic;
      gun_x_coordinate1  : IN     std_logic_vector (7 DOWNTO 0);
      rst_n              : IN     std_logic;
      hit                : OUT    std_logic
   );

-- Declarations

END c6_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c6_t1_hit_detector.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-722-SPC)
--          at - 21:19:40 25.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic;
   SIGNAL hit1 : std_logic;
   SIGNAL q    : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic;

   -- Component Declarations
   COMPONENT coordinates_alien_and_gun
   PORT (
      alien_x_coordinates : IN     std_logic_vector (7 DOWNTO 0);
      gun_x_coordinates   : IN     std_logic_vector (7 DOWNTO 0);
      hit                 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : coordinates_alien_and_gun USE ENTITY alien_game_lib.coordinates_alien_and_gun;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= btn;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   hit <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= dout;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   dout <= btn AND NOT(q) AND hit1;

   -- Instance port mappings.
   U_3 : coordinates_alien_and_gun
      PORT MAP (
         alien_x_coordinates => alien_x_coordinate,
         gun_x_coordinates   => gun_x_coordinate1,
         hit                 => hit1
      );

END struct;
