-- VHDL Entity alien_game_lib.c6_t2_y_coord_vic.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-720-SPC)
--          at - 00:55:35  2.12.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t2_y_coord_vic IS
   PORT( 
      mux_signal : IN     std_logic_vector (3 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c6_t2_y_coord_vic ;

--
-- VHDL Architecture alien_game_lib.c6_t2_y_coord_vic.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-720-SPC)
--          at - 00:55:35  2.12.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c6_t2_y_coord_vic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4 : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   dout <= "00000010";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout1 <= "00000100";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout2 <= "00010000";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout3 <= "00100000";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout4 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'mux'
   u_8combo_proc: PROCESS(dout, dout1, dout2, dout3, dout4, mux_signal)
   BEGIN
      CASE mux_signal IS
      WHEN "0000" => y_coord <= dout;
      WHEN "0001" => y_coord <= dout;
      WHEN "0010" => y_coord <= dout;
      WHEN "0011" => y_coord <= dout;
      WHEN "0100" => y_coord <= dout1;
      WHEN "0101" => y_coord <= dout1;
      WHEN "0110" => y_coord <= dout1;
      WHEN "0111" => y_coord <= dout1;
      WHEN "1000" => y_coord <= dout2;
      WHEN "1001" => y_coord <= dout2;
      WHEN "1010" => y_coord <= dout3;
      WHEN "1011" => y_coord <= dout3;
      WHEN "1100" => y_coord <= dout4;
      WHEN "1101" => y_coord <= dout4;
      WHEN "1110" => y_coord <= dout4;
      WHEN "1111" => y_coord <= dout4;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_8combo_proc;

   -- Instance port mappings.

END struct;
