-- VHDL Entity alien_game_lib.coordinates_alien_and_gun.symbol
--
-- Created:
--          by - mqange.mqange (pikkuhaikara.lin.tuni.fi)
--          at - 15:43:31 11/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY coordinates_alien_and_gun IS
   PORT( 
      alien_x_coordinates : IN     std_logic_vector (7 DOWNTO 0);
      gun_x_coordinates   : IN     std_logic_vector (7 DOWNTO 0);
      hit                 : OUT    std_logic
   );

-- Declarations

END coordinates_alien_and_gun ;

--
-- VHDL Architecture alien_game_lib.coordinates_alien_and_gun.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-722-SPC)
--          at - 20:12:20 25.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF coordinates_alien_and_gun IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout   : std_logic;
   SIGNAL dout0  : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout10 : std_logic;
   SIGNAL dout11 : std_logic;
   SIGNAL dout12 : std_logic;
   SIGNAL dout13 : std_logic;
   SIGNAL dout14 : std_logic;
   SIGNAL dout15 : std_logic;
   SIGNAL dout16 : std_logic;
   SIGNAL dout17 : std_logic;
   SIGNAL dout18 : std_logic;
   SIGNAL dout19 : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout20 : std_logic;
   SIGNAL dout21 : std_logic;
   SIGNAL dout22 : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL dout6  : std_logic;
   SIGNAL dout7  : std_logic;
   SIGNAL dout8  : std_logic;
   SIGNAL dout9  : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'split'
   SIGNAL mw_U_1temp_din : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   hit <= NOT(dout) AND NOT(dout1) AND NOT(dout2) AND NOT(dout3)
          AND NOT(dout4) AND NOT(dout5) AND NOT(dout6) AND NOT(dout7);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= alien_x_coordinates;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(7 DOWNTO 0);
      dout0 <= temp_din(0);
      dout8 <= temp_din(1);
      dout9 <= temp_din(2);
      dout10 <= temp_din(3);
      dout11 <= temp_din(4);
      dout12 <= temp_din(5);
      dout13 <= temp_din(6);
      dout14 <= temp_din(7);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'split'
   mw_U_1temp_din <= gun_x_coordinates;
   u_1combo_proc: PROCESS (mw_U_1temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_1temp_din(7 DOWNTO 0);
      dout22 <= temp_din(0);
      dout21 <= temp_din(1);
      dout20 <= temp_din(2);
      dout19 <= temp_din(3);
      dout18 <= temp_din(4);
      dout17 <= temp_din(5);
      dout16 <= temp_din(6);
      dout15 <= temp_din(7);
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'xnor'
   dout <= dout0 XOR dout22;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'xnor'
   dout1 <= dout8 XOR dout21;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'xnor'
   dout2 <= dout9 XOR dout20;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'xnor'
   dout3 <= dout13 XOR dout19;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'xnor'
   dout4 <= dout10 XOR dout18;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'xnor'
   dout5 <= dout11 XOR dout17;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'xnor'
   dout6 <= dout12 XOR dout16;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'xnor'
   dout7 <= dout14 XOR dout15;

   -- Instance port mappings.

END struct;
