-- VHDL Entity alien_game_lib.right_shifter.symbol
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-705-SPC)
--          at - 20:22:32 30.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY right_shifter IS
   PORT( 
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END right_shifter ;

--
-- VHDL Architecture alien_game_lib.right_shifter.struct
--
-- Created:
--          by - mqange.UNKNOWN (HTC219-705-SPC)
--          at - 20:22:32 30.11.2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF right_shifter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0  : std_logic;
   SIGNAL din2  : std_logic;
   SIGNAL din4  : std_logic;
   SIGNAL din6  : std_logic;
   SIGNAL din7  : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout6 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'split'
   SIGNAL mw_U_1temp_din : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   din7 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_0' of 'merge'
   data_out <= din7 & din6 & dout6 & din4 & dout4 & din2 & dout2 & din0;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'split'
   mw_U_1temp_din <= data_in;
   u_1combo_proc: PROCESS (mw_U_1temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_1temp_din(7 DOWNTO 0);
      din0 <= temp_din(1);
      dout2 <= temp_din(2);
      din2 <= temp_din(3);
      dout4 <= temp_din(4);
      din4 <= temp_din(5);
      dout6 <= temp_din(6);
      din6 <= temp_din(7);
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
